# Practice SQL Database types

Fill out the code, as necessary, below based on the directions in Canvas.

As an independent data science consultant tasked with designing and implementing a database for a school, your approach must balance practicality with strategic foresight. This task is not just about creating a database that functions correctly today, but about developing a system that will remain effective as the school grows and its needs evolve. The primary objective is to build a robust, flexible database that seamlessly manages essential information, including student and staff contact details, academic records, class rosters, and attendance logs.

To achieve this, you'll need to carefully consider the structure and relationships of the data from the outset. The database should be normalized to avoid redundancy and ensure data integrity, making it easier to maintain, query, and scale in the future. The design process involves identifying key entities (such as students, staff, courses, and grades) and mapping how they will interact within the database, which requires not only a strong understanding of the data itself but also foresight into how the data might need to be accessed, updated, and analyzed over time.

In this particular implementation, you are working within a Python environment, leveraging the `sqlite3` module to create and manipulate the database. SQLite is a powerful, lightweight, and self-contained SQL database engine that is well-suited for this task due to its simplicity and ease of integration with Python. It allows you to create a local database file (`school.sqlite`) that can be easily managed and queried directly from your Python scripts.

The process begins by setting up the database file and establishing a connection to it, followed by designing the schema, which involves creating tables to represent the different entities within the school's ecosystem. Each table must be carefully structured with appropriate columns and data types to capture the necessary information. For instance, the `contactInfo` table should include columns for first name, last name, role (indicating whether the person is a student or a staff member), and address details. Each entry in the table is uniquely identified by a primary key, ensuring that records can be accurately referenced and related across different tables.

As you populate the tables, it's crucial to write efficient, secure SQL queries to insert, update, and retrieve data. This process often involves iterating over datasets (like lists of dictionaries) and carefully formatting SQL commands to prevent errors such as SQL injection or data corruption. Additionally, you must implement measures to address potential issues, such as duplicate records or data updates, to ensure the database remains accurate and reliable.

Beyond immediate implementation, it's essential to keep the school's future needs in mind, which includes designing the database to accommodate new features, such as additional tables for attendance tracking or extracurricular activities, and ensuring that it can handle increasing data volume as the school grows. Moreover, the database should be structured to facilitate easy integration with other systems, such as learning management systems or student information systems, which may be added in the future.

In summary, your role as a data science consultant involves not only the technical design of the database but also strategic planning to ensure the system is scalable, secure, and able to meet the school's long-term needs. By carefully designing the database schema, implementing best practices in SQL, and considering future expansions, you will create a robust foundation that supports the school's operational and analytical requirements.

In [9]:
!ls

contact_list.pickle dsc_c1w1m5.ipynb    school.sqlite

Instructions

1. Creating the database: Once you've put a little thought into how you might design your database, it's time to create it! Start by importing the necessary packages. Then, create a database called school.sqlite.

In [10]:
import sqlite3

# Create (or connect to) the database file named school.sqlite
conn = sqlite3.connect('school.sqlite')

# Create a cursor object to execute SQL commands
cur = conn.cursor()

In [11]:
!ls

contact_list.pickle dsc_c1w1m5.ipynb    school.sqlite

2. Create a table for contact information: call it contactInfo to store contact information for both students and staff. Be sure to include columns for first name, last name, role (student/staff), telephone number, street, city, state, and zip code. Be sure also to create a primary key for the table.

In [12]:
#Creating the contactInfo table
cur.execute( """ 
CREATE TABLE contactInfo (
        id INTEGER PRIMARY KEY,
        firstName TEXT,
        lastName TEXT,
        role TEXT,
        telephone TEXT,
        street TEXT,
        city TEXT,
        state TEXT,
        zipcode TEXT )
""" )

Populate the table:

a. Below, the code is provided to load a list of dictionaries. Briefly examine the list. Each dictionary in the list will serve as an entry for your contact info table. Once you've briefly investigated the structure of this data, write a for loop to iterate through the list and create an entry in your table for each person's contact info.

b. Afterwards, query the table to ensure it is populated.

In [13]:
# Load the list of dictionaries; just run this cell
import pickle

with open('contact_list.pickle', 'rb') as f:
    contacts = pickle.load(f)

In [14]:
contacts

[{'firstName': 'Christine',
  'lastName': 'Holden',
  'role': 'staff',
  'telephone ': 2035687697,
  'street': '1672 Whitman Court',
  'city': 'Stamford',
  'state': 'CT',
  'zipcode ': '06995'},
 {'firstName': 'Christopher',
  'lastName': 'Warren',
  'role': 'student',
  'telephone ': 2175150957,
  'street': '1935 University Hill Road',
  'city': 'Champaign',
  'state': 'IL',
  'zipcode ': '61938'},
 {'firstName': 'Linda',
  'lastName': 'Jacobson',
  'role': 'staff',
  'telephone ': 4049446441,
  'street': '479 Musgrave Street',
  'city': 'Atlanta',
  'state': 'GA',
  'zipcode ': '30303'},
 {'firstName': 'Andrew',
  'lastName': 'Stepp',
  'role': 'student',
  'telephone ': 7866419252,
  'street': '2981 Lamberts Branch Road',
  'city': 'Hialeah',
  'state': 'Fl',
  'zipcode ': '33012'},
 {'firstName': 'Jane',
  'lastName': 'Evans',
  'role': 'student',
  'telephone ': 3259909290,
  'street': '1461 Briarhill Lane',
  'city': 'Abilene',
  'state': 'TX',
  'zipcode ': '79602'},
 {'firstName': 'Jane',
  'lastName': 'Evans',
  'role': 'student',
  'telephone ': 3259909290,
  'street': '1461 Briarhill Lane',
  'city': 'Abilene',
  'state': 'TX',
  'zipcode ': '79602'},
 {'firstName': 'Mary',
  'lastName': 'Raines',
  'role': 'student',
  'telephone ': 9075772295,
  'street': '3975 Jerry Toth Drive',
  'city': 'Ninilchik',
  'state': 'AK',
  'zipcode ': '99639'},
 {'firstName': 'Ed',
  'lastName': 'Lyman',
  'role': 'student',
  'telephone ': 5179695576,
  'street': '3478 Be Sreet',
  'city': 'Lansing',
  'state': 'MI',
  'zipcode ': '48933'}]

In [15]:
counter = 0

# Use < instead of <= to stay within the list boundaries
while counter < len(contacts):
    contact = contacts[counter]
    
    # Extract values (watch out for that space in 'zipcode ')
    data = (
        contact['firstName'], 
        contact['lastName'], 
        contact['role'], 
        contact['telephone '], 
        contact['street'], 
        contact['city'], 
        contact['state'], 
        contact['zipcode '] 
    )

    # Use ? placeholders for the database driver to handle
    query = """INSERT INTO contactInfo 
               (firstName, lastName, role, telephone, street, city, state, zipcode)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?);"""
    
    cur.execute(query, data)
    
    # Don't forget to increment your counter!
    counter += 1

4. Commit your changes to the database: persist them by committing them.

In [16]:
# Commit our changes to the databaase
conn.commit()

5. Create a table for Student Grades: Create a new table in the database called "grades". In the table, include the following fields: userId, courseId, grade. ** This problem is a bit trickier and will require a dual key. (A nuance you have yet to see.) Here's how to do that:

```python

CREATE TABLE table_name(
   column_1 INTEGER NOT NULL,
   column_2 INTEGER NOT NULL,
   ...
   PRIMARY KEY(column_1,column_2,...)
);

# Create the grades table
cur.execute("""CREATE TABLE grades (
                                    userId INTEGER NOT NULL,
                                    courseId INTEGER NOT NULL,
                                    grade INTEGER,
                                    PRIMARY KEY(userId, courseId)
                                    );
            """)
```

In [17]:
# Create the grades table
cur.execute("""CREATE TABLE grades (
                                    userId INTEGER NOT NULL,
                                    courseId INTEGER NOT NULL,
                                    grade INTEGER,
                                    PRIMARY KEY(userId, courseId)
                                    );
            """)

In [19]:
cur.execute(""" SELECT * FROM contactInfo """).fetchall()

[(1,
  'Christine',
  'Holden',
  'staff',
  '2035687697',
  '1672 Whitman Court',
  'Stamford',
  'CT',
  '06995'),
 (2,
  'Christopher',
  'Warren',
  'student',
  '2175150957',
  '1935 University Hill Road',
  'Champaign',
  'IL',
  '61938'),
 (3,
  'Linda',
  'Jacobson',
  'staff',
  '4049446441',
  '479 Musgrave Street',
  'Atlanta',
  'GA',
  '30303'),
 (4,
  'Andrew',
  'Stepp',
  'student',
  '7866419252',
  '2981 Lamberts Branch Road',
  'Hialeah',
  'Fl',
  '33012'),
 (5,
  'Jane',
  'Evans',
  'student',
  '3259909290',
  '1461 Briarhill Lane',
  'Abilene',
  'TX',
  '79602'),
 (6,
  'Jane',
  'Evans',
  'student',
  '3259909290',
  '1461 Briarhill Lane',
  'Abilene',
  'TX',
  '79602'),
 (7,
  'Mary',
  'Raines',
  'student',
  '9075772295',
  '3975 Jerry Toth Drive',
  'Ninilchik',
  'AK',
  '99639'),
 (8,
  'Ed',
  'Lyman',
  'student',
  '5179695576',
  '3478 Be Sreet',
  'Lansing',
  'MI',
  '48933')]

6. Remove duplicate entries: An analyst just realized that there is a duplicate entry in the contactInfo table! Find and remove it.

In [20]:
cur.execute('''DELETE FROM contactInfo
                 WHERE id = 5;
           ''')

In [24]:
cur.execute(""" SELECT * FROM contactInfo """).fetchall()

[(1,
  'Christine',
  'Holden',
  'staff',
  '2035687697',
  '1672 Whitman Court',
  'Stamford',
  'CT',
  '06995'),
 (2,
  'Christopher',
  'Warren',
  'student',
  '2175150957',
  '1935 University Hill Road',
  'Champaign',
  'IL',
  '61938'),
 (3,
  'Linda',
  'Jacobson',
  'staff',
  '4049446441',
  '479 Musgrave Street',
  'Atlanta',
  'GA',
  '30303'),
 (4,
  'Andrew',
  'Stepp',
  'student',
  '7866419252',
  '2981 Lamberts Branch Road',
  'Hialeah',
  'Fl',
  '33012'),
 (6,
  'Jane',
  'Evans',
  'student',
  '3259909290',
  '1461 Briarhill Lane',
  'Abilene',
  'TX',
  '79602'),
 (7,
  'Mary',
  'Raines',
  'student',
  '9075772295',
  '3975 Jerry Toth Drive',
  'Ninilchik',
  'AK',
  '99639'),
 (8,
  'Ed',
  'Lyman',
  'student',
  '5179695576',
  '3478 Be Sreet',
  'Lansing',
  'MI',
  '48933')]

7. Updating an address: Ed Lyman just moved to 2910 Simpson Avenue, York, PA 17403. Update his address accordingly.

In [32]:
cur.execute( """UPDATE contactInfo SET street = '2910 Simpson Avenue', 
                    city = 'York', 
                    state = 'PA',
                    zipcode  = '17403'
                    WHERE firstName = 'Ed';""" )

In [33]:
cur.execute(""" SELECT * FROM contactInfo """).fetchall()

[(1,
  'Christine',
  'Holden',
  'staff',
  '2035687697',
  '1672 Whitman Court',
  'Stamford',
  'CT',
  '06995'),
 (2,
  'Christopher',
  'Warren',
  'student',
  '2175150957',
  '1935 University Hill Road',
  'Champaign',
  'IL',
  '61938'),
 (3,
  'Linda',
  'Jacobson',
  'staff',
  '4049446441',
  '479 Musgrave Street',
  'Atlanta',
  'GA',
  '30303'),
 (4,
  'Andrew',
  'Stepp',
  'student',
  '7866419252',
  '2981 Lamberts Branch Road',
  'Hialeah',
  'Fl',
  '33012'),
 (6,
  'Jane',
  'Evans',
  'student',
  '3259909290',
  '1461 Briarhill Lane',
  'Abilene',
  'TX',
  '79602'),
 (7,
  'Mary',
  'Raines',
  'student',
  '9075772295',
  '3975 Jerry Toth Drive',
  'Ninilchik',
  'AK',
  '99639'),
 (8,
  'Ed',
  'Lyman',
  'student',
  '5179695576',
  '2910 Simpson Avenue',
  'York',
  'PA',
  '17403')]

8. Commit your changes to the database: persist them by committing.

In [34]:
conn.commit()

In [35]:
conn.close()


# SOLUTION

In [ ]:
cur.execute(""" DROP TABLE contactInfo """)

In [ ]:
cur.execute(""" DROP TABLE grades """)

Step 1

In [1]:
# Import necessary packages
import sqlite3
import pandas as pd

# Create the database school.sqlite
conn = sqlite3.Connection('school.sqlite')

Step 2

In [4]:
cur = conn.cursor()
cur.execute("""CREATE TABLE contactInfo (
                                        userId INTEGER PRIMARY KEY,
                                        firstName TEXT,
                                        lastName TEXT,
                                        role TEXT,
                                        telephone INTEGER,
                                        street TEXT,
                                        city TEXT,
                                        state TEXT,
                                        zipcode TEXT
                                        );
            """)

Step 3

In [5]:
# Load the list of dictionaries; just run this cell
import pickle

with open('contact_list.pickle', 'rb') as f:
    contacts = pickle.load(f)

# Iterate over the contact list and populate the contactInfo table here
for contact in contacts:
    firstName = contact['firstName']
    lastName = contact['lastName']
    role = contact['role']
    telephone  = contact['telephone ']
    street = contact['street']
    city = contact['city']
    state = contact['state']
    zipcode  = contact['zipcode ']
    cur.execute("""INSERT INTO contactInfo (firstName, lastName, role, telephone, street, city, state, zipcode) 
                  VALUES ('{}', '{}', '{}', '{}', '{}', '{}', '{}', '{}');
                """.format(firstName, lastName, role, telephone, street, city, state, zipcode) )

Query the Table to Ensure it is populated

In [6]:
cur.execute("""SELECT * 
               FROM contactInfo;""")
df = pd.DataFrame(cur.fetchall())
df.columns = [x[0] for x in cur.description]
df

,userId,firstName,lastName,role,telephone,street,city,state,zipcode
0,1,Christine,Holden,staff,2035687697,1672 Whitman Court,Stamford,CT,06995
1,2,Christopher,Warren,student,2175150957,1935 University Hill Road,Champaign,IL,61938
2,3,Linda,Jacobson,staff,4049446441,479 Musgrave Street,Atlanta,GA,30303
3,4,Andrew,Stepp,student,7866419252,2981 Lamberts Branch Road,Hialeah,Fl,33012
4,5,Jane,Evans,student,3259909290,1461 Briarhill Lane,Abilene,TX,79602
5,6,Jane,Evans,student,3259909290,1461 Briarhill Lane,Abilene,TX,79602
6,7,Mary,Raines,student,9075772295,3975 Jerry Toth Drive,Ninilchik,AK,99639
7,8,Ed,Lyman,student,5179695576,3478 Be Sreet,Lansing,MI,48933

Step 4

In [7]:
conn.commit()

Step 5

We want the SQL code to look like this:

```sql
CREATE TABLE table_name(
   column_1 INTEGER NOT NULL,
   column_2 INTEGER NOT NULL,
   ...
   PRIMARY KEY(column_1,column_2,...)
);
```

In [10]:
# Create the grades table
cur.execute("""CREATE TABLE grades (
                                    userId INTEGER NOT NULL,
                                    courseId INTEGER NOT NULL,
                                    grade INTEGER,
                                    PRIMARY KEY(userId, courseId)
                                    );
            """)

 Step 6

In [11]:
# Find the duplicate entry
cur.execute("""SELECT firstName, lastName, telephone, COUNT(*) 
               FROM contactInfo
               GROUP BY firstName, lastName, telephone
               HAVING COUNT(*) > 1;""").fetchall()

[('Jane', 'Evans', 3259909290, 2)]

In [12]:
# Delete the duplicate entry
cur.execute("""DELETE FROM contactInfo 
               WHERE telephone = 3259909290;""")

# Check that the duplicate entry was removed 
cur.execute("""SELECT firstName, lastName, telephone, COUNT(*) 
               FROM contactInfo
               GROUP BY firstName, lastName, telephone
               HAVING COUNT(*) > 1;""").fetchall()

[]

 Step 7

In [13]:
# Update Ed's address
cur.execute("""UPDATE contactInfo
               SET street = "2910 Simpson Avenue",
                   city = 'York',
                   state = 'PA',
                   zipcode = '17403'
               WHERE firstName = "Ed" AND lastName = "Lyman";""")

# Query the database to ensure the change was made
cur.execute("""SELECT * 
               FROM contactInfo;""")
df = pd.DataFrame(cur.fetchall())
df.columns = [x[0] for x in cur.description]
df

,userId,firstName,lastName,role,telephone,street,city,state,zipcode
0,1,Christine,Holden,staff,2035687697,1672 Whitman Court,Stamford,CT,06995
1,2,Christopher,Warren,student,2175150957,1935 University Hill Road,Champaign,IL,61938
2,3,Linda,Jacobson,staff,4049446441,479 Musgrave Street,Atlanta,GA,30303
3,4,Andrew,Stepp,student,7866419252,2981 Lamberts Branch Road,Hialeah,Fl,33012
4,7,Mary,Raines,student,9075772295,3975 Jerry Toth Drive,Ninilchik,AK,99639
5,8,Ed,Lyman,student,5179695576,2910 Simpson Avenue,York,PA,17403

Step 8

In [14]:
conn.commit()

In [15]:
# Remember to close the connection when you are done
conn.close()